version: "3.7"
services:
  app:
    build:
      args:
        user: miracle
        uid: 1000
      context: docker/php-fpm/
      dockerfile: Dockerfile
    image: article
    container_name: article-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - article

  db:
    image: mysql
    container_name: article-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - article

  nginx:
    image: nginx:alpine
    container_name: article-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - article

  node:
    image: node:alpine
    container_name: article-node
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    networks:
      - article
        
networks:
  article:
    driver: bridge